// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVSCOth507AtsigWn22-vwolRvSHHtXOc',
    appId: '1:128805846731:web:2d4e7c08637e775113654e',
    messagingSenderId: '128805846731',
    projectId: 'mine-chrz95',
    authDomain: 'mine-chrz95.firebaseapp.com',
    storageBucket: 'mine-chrz95.appspot.com',
    measurementId: 'G-9XS7WWP43V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb2mVyxvW720Vf96sDgzwSW1bh0LcUmKM',
    appId: '1:128805846731:android:4b3758395de87fc913654e',
    messagingSenderId: '128805846731',
    projectId: 'mine-chrz95',
    storageBucket: 'mine-chrz95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDebfIzHaCX2542cBMkm8RVhEC5DNUKeVI',
    appId: '1:128805846731:ios:86a966a79192ccaa13654e',
    messagingSenderId: '128805846731',
    projectId: 'mine-chrz95',
    storageBucket: 'mine-chrz95.appspot.com',
    iosClientId: '128805846731-46jl2fpqlele0fv1609ao4b0n51cfsnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDebfIzHaCX2542cBMkm8RVhEC5DNUKeVI',
    appId: '1:128805846731:ios:86a966a79192ccaa13654e',
    messagingSenderId: '128805846731',
    projectId: 'mine-chrz95',
    storageBucket: 'mine-chrz95.appspot.com',
    iosClientId: '128805846731-46jl2fpqlele0fv1609ao4b0n51cfsnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );
}
